### ISSUE TITLE
API key not found with Azure provider

### ISSUE THREAD

**Issue by duskybomb** [stanford-oval/chainlite#10]
When I use the azure provider, I am getting the following error:
```
Retrying langchain_community.chat_models.litellm.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: litellm.APIError: AzureException APIError - Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_API_KEY` or `AZURE_OPENAI_AD_TOKEN` environment variables..
```

I think my config file is correctly set up. I looked into the code and maybe this is the culprit:
https://github.com/stanford-oval/chainlite/blob/d38495189c654d744bb6e890cc6b06240de10316/chainlite/llm_generate.py#L426

`ChatLiteLLM` doesn't take `api_key` as a param, instead it take `azure_api_key` for azure, and `openai_api_key` for OpenAI and similarly for others:
https://python.langchain.com/api_reference/community/chat_models/langchain_community.chat_models.litellm.ChatLiteLLM.html#langchain_community.chat_models.litellm.ChatLiteLLM.azure_api_key

**Comment by s-jse** [comment]
Should be fixed in the latest commit. I also added tests for Azure OpenAI.
