### ISSUE TITLE
Assumes llm_config.yaml is present at the root of the project

### ISSUE THREAD

**Issue by duskybomb** [stanford-oval/chainlite#8]
I have code that looks like this:
```
import os
from chainlite import llm_generation_chain, load_config_from_file

current_dir = os.path.dirname(os.path.realpath(__file__))
load_config_from_file(os.path.join(current_dir, "llm_config.yaml"))
```

When I run it I get the following error:

```
  File "/home/usr/worksheets/worksheets/environment.py", line 14, in <module>
    from chainlite import llm_generation_chain, load_config_from_file
  File "/home/usr/.conda/envs/worksheets-chainlite/lib/python3.11/site-packages/chainlite/__init__.py", line 3, in <module>
    from .llm_config import (
  File "/home/usr/.conda/envs/worksheets-chainlite/lib/python3.11/site-packages/chainlite/llm_config.py", line 148, in <module>
    load_config_from_file("./llm_config.yaml")
  File "/home/usr/.conda/envs/worksheets-chainlite/lib/python3.11/site-packages/chainlite/llm_config.py", line 81, in load_config_from_file
    with open(config_file, "r") as config_file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './llm_config.yaml'
```

The library assumes that the project's root directory contains a `./llm_config.yaml` file and tries to load it even if `load_config_from_file()` is used.

I believe the issue is L148 in `llm_config.py`, which hardcodes the config file path.

**Comment by duskybomb** [comment]
@s-jse why do we need this line: https://github.com/stanford-oval/chainlite/blob/c4adcfb2d7d6195757d84dec8171d34a081dfa01/chainlite/llm_config.py#L185

This assumes that `llm_config.yaml` should always be present in the root. Can we just remove this line?

**Comment by s-jse** [comment]
I put it there because some code bases don't have a good starting point to put `load_config_from_file()` in, such that it always gets loaded first. Any suggestions?

**Comment by s-jse** [comment]
@duskybomb can you see if it is fixed now in the `main` branch?

**Comment by duskybomb** [comment]
Yes, I think this is fixed! Closing the issue!
